### ISSUE TITLE
Add suppport for docker bind mounts

### ISSUE THREAD

**Issue by Akruidenberg** [jabuwu/docker-volume-backup#3]
In my server, all my volumes are bind mounts. This tool only supports docker volumes.

It would be nice to add such path added to the web interface. Now, this tool is useless for me, but the concept is really nice!

**Comment by jabuwu** [comment]
Hello, thank you for your interest! Please try the latest commit, c394993f7d49857d63d43dfeaefdbd13b1334e74.

Use this tool with caution as there may be bugs! I tried several scenarios and I believe it's all working properly. If you run into issues let me know here, otherwise I will close this issue.

**Comment by Akruidenberg** [comment]
Its not working well. All my subfolders are also mounted. However, is to not select a volume. No check boxes.

**Comment by jabuwu** [comment]
You must add a schedule to enable automatic backups. Go to the "Schedules" page and press the +.

Each volume will need its own backup schedule.

**Comment by Akruidenberg** [comment]
> You must add a schedule to enable automatic backups. Go to the "Schedules" page and press the +.
> 
> Each volume will need its own backup schedule.

For testing, i only mounting one volume. However. Every subfolder is visible in the web interface.

**Comment by jabuwu** [comment]
Are you using local storage? You should choose a path with no files in it. That is where the backup files will be created.

For example, you could use `/backups` as the storage path. When you back up the volume, a tgz file will be created in `/backups`

If you are not using local storage, I need to see a screenshot of the problem.

**Comment by Akruidenberg** [comment]
![afbeelding](https://user-images.githubusercontent.com/18529293/117158058-60d71800-adbf-11eb-93da-5e14b15e7dcd.png)

Only one volume is mounted.....

**Comment by jabuwu** [comment]
If you click on the number under "Containers" in the table you can see which containers have a volume mounted. Perhaps you have several stopped containers that mount the volumes?

In any case, it won't cause any problems and you can ignore them. That's why I added the pin feature. You can pin the important volumes to the top of the page by pressing the star.

There's not a lot I can do about it. I'm going by what Docker tells me is mounted.
https://github.com/jabuwu/docker-volume-backup/blob/f299cc35ab35c1dbaddcd8e2ce132d940a70c4ca/packages/dvb/src/docker/index.ts#L368-L378

**Comment by jabuwu** [comment]
I'm closing this as I believe the original request has been implemented.
